apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    io.kompose.service: api
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
spec:
  type: NodePort
  selector:
    io.kompose.service: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
