apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    io.kompose.service: web
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
spec:
  type: NodePort
  selector:
    io.kompose.service: web
  ports:
    - name: http
      port: 80         # クラスタ内の公開ポート
      targetPort: 80   # Pod(nginx) のポート
      nodePort: 30080  # ローカルからの入口（固定）
